/*                                                                */
/* Questo file  stato creato da T.I.P., scritto da Fochi Michele */
/*                                                                */
/*                                                                */
/* Le procedure "clrscr()", "textattr()", "gotoxy()" e            */
/* "cprintf()" e la costante "LIGHTGRAY" sono nella unit CONIO.H  */
/*                                                                */
/* Per eseguire il programma occorre quindi la seguente linea     */
/* di codice (nelle prime righe del programma):                   */
/*                                                                */
/*     #include <conio.h>                                         */

void C2()

  { /* C2 */

  /* Cancello lo schermo */
  textattr(LIGHTGRAY);
  clrscr();

  /* Ora viene riempito lo schermo */

  textattr(14);
  cprintf("ֹֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽ»");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        ששששששששששששששששששששששששששששששששששששששששששששששששששששששששששש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתת");
  textattr(13);
  cprintf("Úִִִִִִִִִִִִִִ¿");
  textattr(15);
  cprintf("תתתת");
  textattr(11);
  cprintf("Úִִִִִִ¿");
  textattr(15);
  cprintf("תתתתתתת");
  textattr(12);
  cprintf("Úִִִִִִִִִִִִִ¿");
  textattr(15);
  cprintf("תתתתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתת");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("°°°°°°°°°°°°°°");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("תתתת");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("±±±±±±");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("תתתתתתת");
  textattr(12);
  cprintf("³");
  textattr(15);
  cprintf("²²²²²²²²²²²²²");
  textattr(12);
  cprintf("ְ¿");
  textattr(15);
  cprintf("תתתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתת");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("°°");
  textattr(13);
  cprintf("Úִִ¿");
  textattr(15);
  cprintf("°°");
  textattr(13);
  cprintf("Úִִ¿");
  textattr(15);
  cprintf("°°");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("תתתת");
  textattr(11);
  cprintf("ְִ¿");
  textattr(15);
  cprintf("±±");
  textattr(11);
  cprintf("ÚִÙ");
  textattr(15);
  cprintf("תתתתתתת");
  textattr(12);
  cprintf("ְִ¿");
  textattr(15);
  cprintf("²²Úִִִִִִ¿²²");
  textattr(12);
  cprintf("ְ¿");
  textattr(15);
  cprintf("תתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתת");
  textattr(13);
  cprintf("ְִִÙ");
  textattr(15);
  cprintf("תת");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("°°");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("תת");
  textattr(13);
  cprintf("ְִִÙ");
  textattr(15);
  cprintf("תתתתתת");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("±±");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("תתתתתתתתתתת");
  textattr(12);
  cprintf("³");
  textattr(15);
  cprintf("²²³תתתתתתֶ ²²");
  textattr(12);
  cprintf("³");
  textattr(15);
  cprintf("תתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתתתתתתתת");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("°°");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("תתתתתתתתתתתת");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("±±");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("תתתתתתתתתתת");
  textattr(12);
  cprintf("³");
  textattr(15);
  cprintf("²²ְִִִִִִÙ²²");
  textattr(12);
  cprintf("ÚÙ");
  textattr(15);
  cprintf("תתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתתתתתתתת");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("°°");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("תתתתתתתתתתתת");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("±±");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("תתתתתתתתתתת");
  textattr(12);
  cprintf("³");
  textattr(15);
  cprintf("²²²²²²²²²²²");
  textattr(12);
  cprintf("ÚÙ");
  textattr(15);
  cprintf("תתתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתתתתתתתת");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("°°");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("תתתתתתתתתתתת");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("±±");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("תתתתתתתתתתת");
  textattr(12);
  cprintf("³");
  textattr(15);
  cprintf("²²");
  textattr(12);
  cprintf("ÚִִִִִִִִÙ");
  textattr(15);
  cprintf("תתתתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתתתתתת");
  textattr(13);
  cprintf("ÚִÙ");
  textattr(15);
  cprintf("°°");
  textattr(13);
  cprintf("ְִ¿");
  textattr(15);
  cprintf("תתתתתתתת");
  textattr(11);
  cprintf("ÚִÙ");
  textattr(15);
  cprintf("±±");
  textattr(11);
  cprintf("ְִ¿");
  textattr(15);
  cprintf("תתתתתתת");
  textattr(12);
  cprintf("ÚִÙ");
  textattr(15);
  cprintf("²²");
  textattr(12);
  cprintf("ְִ¿");
  textattr(15);
  cprintf("תתתתתתתתתתתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתתתתתת");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("°°°°°°");
  textattr(13);
  cprintf("³");
  textattr(15);
  cprintf("תTEXTתתת");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("±±±±±±");
  textattr(11);
  cprintf("³");
  textattr(15);
  cprintf("תIMAGEת");
  textattr(12);
  cprintf("³");
  textattr(15);
  cprintf("²²²²²²");
  textattr(12);
  cprintf("³");
  textattr(15);
  cprintf("תPROCESSORתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתתתתתת");
  textattr(13);
  cprintf("ְִִִִִִÙ");
  textattr(15);
  cprintf("תתתתתתתת");
  textattr(11);
  cprintf("ְִִִִִִÙ");
  textattr(15);
  cprintf("תתתתתתת");
  textattr(12);
  cprintf("ְִִִִִִÙ");
  textattr(15);
  cprintf("תתתתתתתתתתתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        שתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        ששששששששששששששששששששששששששששששששששששששששששששששששששששששששששש           ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        FOCHI MICHELE & AMATULLI DAVIDE                                       ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("        VERSIONE 1.0                                                          ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("÷");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("÷");
  textattr(14);
  cprintf("ָֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽ¼");

  } /* C2 */

