/*                                                                */
/* Questo file  stato creato da T.I.P., scritto da Fochi Michele */
/*                                                                */
/*                                                                */
/* Le procedure "clrscr()", "textattr()", "gotoxy()" e            */
/* "cprintf()" e la costante "LIGHTGRAY" sono nella unit CONIO.H  */
/*                                                                */
/* Per eseguire il programma occorre quindi la seguente linea     */
/* di codice (nelle prime righe del programma):                   */
/*                                                                */
/*     #include <conio.h>                                         */

void C3()

  { /* C3 */

  /* Cancello lo schermo */
  textattr(LIGHTGRAY);
  clrscr();

  /* Ora viene riempito lo schermo */


  textattr(11);
  gotoxy(33,6);
  cprintf("Úִִִִִִ¿");
  gotoxy(33,7);
  cprintf("³");
  gotoxy(40,7);
  cprintf("³");
  gotoxy(33,8);
  cprintf("ְִ¿");
  gotoxy(38,8);
  cprintf("ÚִÙ");
  gotoxy(35,9);
  cprintf("³");
  gotoxy(38,9);
  cprintf("³");
  gotoxy(35,10);
  cprintf("³");
  gotoxy(38,10);
  cprintf("³");
  gotoxy(35,11);
  cprintf("³");
  gotoxy(38,11);
  cprintf("³");
  gotoxy(35,12);
  cprintf("³");
  gotoxy(38,12);
  cprintf("³");
  gotoxy(33,13);
  cprintf("ÚִÙ");
  gotoxy(38,13);
  cprintf("ְִ¿");
  gotoxy(33,14);
  cprintf("³");
  gotoxy(40,14);
  cprintf("³");
  gotoxy(33,15);
  cprintf("ְִִִִִִÙ");

  textattr(12);
  gotoxy(48,6);
  cprintf("Úִִִִִִִִִִִִִ¿");
  gotoxy(48,7);
  cprintf("³");
  gotoxy(62,7);
  cprintf("ְ¿");
  gotoxy(48,8);
  cprintf("ְִ¿");
  gotoxy(63,8);
  cprintf("ְ¿");
  gotoxy(50,9);
  cprintf("³");
  gotoxy(64,9);
  cprintf("³");
  gotoxy(50,10);
  cprintf("³");
  gotoxy(63,10);
  cprintf("ÚÙ");
  gotoxy(50,11);
  cprintf("³");
  gotoxy(62,11);
  cprintf("ÚÙ");
  gotoxy(50,12);
  cprintf("³");
  gotoxy(53,12);
  cprintf("ÚִִִִִִִִÙ");
  gotoxy(48,13);
  cprintf("ÚִÙ");
  gotoxy(53,13);
  cprintf("ְִ¿");
  gotoxy(48,14);
  cprintf("³");
  gotoxy(55,14);
  cprintf("³");
  gotoxy(48,15);
  cprintf("ְִִִִִִÙ");

  textattr(13);
  gotoxy(13,6);
  cprintf("Úִִִִִִִִִִִִִִ¿");
  gotoxy(13,7);
  cprintf("³");
  gotoxy(28,7);
  cprintf("³");
  gotoxy(13,8);
  cprintf("³");
  gotoxy(16,8);
  cprintf("Úִִ¿");
  gotoxy(22,8);
  cprintf("Úִִ¿");
  gotoxy(28,8);
  cprintf("³");
  gotoxy(13,9);
  cprintf("ְִִÙ");
  gotoxy(19,9);
  cprintf("³");
  gotoxy(22,9);
  cprintf("³");
  gotoxy(25,9);
  cprintf("ְִִÙ");
  gotoxy(19,10);
  cprintf("³");
  gotoxy(22,10);
  cprintf("³");
  gotoxy(19,11);
  cprintf("³");
  gotoxy(22,11);
  cprintf("³");
  gotoxy(19,12);
  cprintf("³");
  gotoxy(22,12);
  cprintf("³");
  gotoxy(17,13);
  cprintf("ÚִÙ");
  gotoxy(22,13);
  cprintf("ְִ¿");
  gotoxy(17,14);
  cprintf("³");
  gotoxy(24,14);
  cprintf("³");
  gotoxy(17,15);
  cprintf("ְִִִִִִÙ");

  textattr(14);
  gotoxy(1,1);
  cprintf("ֹֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽ»");
  gotoxy(1,2);
  cprintf("÷");
  gotoxy(80,2);
  cprintf("÷");
  gotoxy(1,3);
  cprintf("÷");
  gotoxy(80,3);
  cprintf("÷");
  gotoxy(1,4);
  cprintf("÷");
  gotoxy(80,4);
  cprintf("÷");
  gotoxy(1,5);
  cprintf("÷");
  gotoxy(80,5);
  cprintf("÷");
  gotoxy(1,6);
  cprintf("÷");
  gotoxy(80,6);
  cprintf("÷");
  gotoxy(1,7);
  cprintf("÷");
  gotoxy(80,7);
  cprintf("÷");
  gotoxy(1,8);
  cprintf("÷");
  gotoxy(80,8);
  cprintf("÷");
  gotoxy(1,9);
  cprintf("÷");
  gotoxy(80,9);
  cprintf("÷");
  gotoxy(1,10);
  cprintf("÷");
  gotoxy(80,10);
  cprintf("÷");
  gotoxy(1,11);
  cprintf("÷");
  gotoxy(80,11);
  cprintf("÷");
  gotoxy(1,12);
  cprintf("÷");
  gotoxy(80,12);
  cprintf("÷");
  gotoxy(1,13);
  cprintf("÷");
  gotoxy(80,13);
  cprintf("÷");
  gotoxy(1,14);
  cprintf("÷");
  gotoxy(80,14);
  cprintf("÷");
  gotoxy(1,15);
  cprintf("÷");
  gotoxy(80,15);
  cprintf("÷");
  gotoxy(1,16);
  cprintf("÷");
  gotoxy(80,16);
  cprintf("÷");
  gotoxy(1,17);
  cprintf("÷");
  gotoxy(80,17);
  cprintf("÷");
  gotoxy(1,18);
  cprintf("÷");
  gotoxy(80,18);
  cprintf("÷");
  gotoxy(1,19);
  cprintf("÷");
  gotoxy(80,19);
  cprintf("÷");
  gotoxy(1,20);
  cprintf("÷");
  gotoxy(80,20);
  cprintf("÷");
  gotoxy(1,21);
  cprintf("÷");
  gotoxy(80,21);
  cprintf("÷");
  gotoxy(1,22);
  cprintf("÷");
  gotoxy(80,22);
  cprintf("÷");
  gotoxy(1,23);
  cprintf("÷");
  gotoxy(80,23);
  cprintf("÷");
  gotoxy(1,24);
  cprintf("ָֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽ¼");

  textattr(15);
  gotoxy(2,2);
  cprintf("                                                                              ");
  gotoxy(2,3);
  cprintf("                                                                              ");
  gotoxy(2,4);
  cprintf("        ששששששששששששששששששששששששששששששששששששששששששששששששששששששששששש           ");
  gotoxy(2,5);
  cprintf("        שתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתש           ");
  gotoxy(2,6);
  cprintf("        שתת");
  gotoxy(29,6);
  cprintf("תתתת");
  gotoxy(41,6);
  cprintf("תתתתתתת");
  gotoxy(63,6);
  cprintf("תתתתתש           ");
  gotoxy(2,7);
  cprintf("        שתת");
  gotoxy(14,7);
  cprintf("°°°°°°°°°°°°°°");
  gotoxy(29,7);
  cprintf("תתתת");
  gotoxy(34,7);
  cprintf("±±±±±±");
  gotoxy(41,7);
  cprintf("תתתתתתת");
  gotoxy(49,7);
  cprintf("²²²²²²²²²²²²²");
  gotoxy(64,7);
  cprintf("תתתתש           ");
  gotoxy(2,8);
  cprintf("        שתת");
  gotoxy(14,8);
  cprintf("°°");
  gotoxy(20,8);
  cprintf("°°");
  gotoxy(26,8);
  cprintf("°°");
  gotoxy(29,8);
  cprintf("תתתת");
  gotoxy(36,8);
  cprintf("±±");
  gotoxy(41,8);
  cprintf("תתתתתתת");
  gotoxy(51,8);
  cprintf("²²Úִִִִִִ¿²²");
  gotoxy(65,8);
  cprintf("תתתש           ");
  gotoxy(2,9);
  cprintf("        שתת");
  gotoxy(17,9);
  cprintf("תת");
  gotoxy(20,9);
  cprintf("°°");
  gotoxy(23,9);
  cprintf("תת");
  gotoxy(29,9);
  cprintf("תתתתתת");
  gotoxy(36,9);
  cprintf("±±");
  gotoxy(39,9);
  cprintf("תתתתתתתתתתת");
  gotoxy(51,9);
  cprintf("²²³תתתתתתֶ ²²");
  gotoxy(65,9);
  cprintf("תתתש           ");
  gotoxy(2,10);
  cprintf("        שתתתתתתתת");
  gotoxy(20,10);
  cprintf("°°");
  gotoxy(23,10);
  cprintf("תתתתתתתתתתתת");
  gotoxy(36,10);
  cprintf("±±");
  gotoxy(39,10);
  cprintf("תתתתתתתתתתת");
  gotoxy(51,10);
  cprintf("²²ְִִִִִִÙ²²");
  gotoxy(65,10);
  cprintf("תתתש           ");
  gotoxy(2,11);
  cprintf("        שתתתתתתתת");
  gotoxy(20,11);
  cprintf("°°");
  gotoxy(23,11);
  cprintf("תתתתתתתתתתתת");
  gotoxy(36,11);
  cprintf("±±");
  gotoxy(39,11);
  cprintf("תתתתתתתתתתת");
  gotoxy(51,11);
  cprintf("²²²²²²²²²²²");
  gotoxy(64,11);
  cprintf("תתתתש           ");
  gotoxy(2,12);
  cprintf("        שתתתתתתתת");
  gotoxy(20,12);
  cprintf("°°");
  gotoxy(23,12);
  cprintf("תתתתתתתתתתתת");
  gotoxy(36,12);
  cprintf("±±");
  gotoxy(39,12);
  cprintf("תתתתתתתתתתת");
  gotoxy(51,12);
  cprintf("²²");
  gotoxy(63,12);
  cprintf("תתתתתש           ");
  gotoxy(2,13);
  cprintf("        שתתתתתת");
  gotoxy(20,13);
  cprintf("°°");
  gotoxy(25,13);
  cprintf("תתתתתתתת");
  gotoxy(36,13);
  cprintf("±±");
  gotoxy(41,13);
  cprintf("תתתתתתת");
  gotoxy(51,13);
  cprintf("²²");
  gotoxy(56,13);
  cprintf("תתתתתתתתתתתתש           ");
  gotoxy(2,14);
  cprintf("        שתתתתתת");
  gotoxy(18,14);
  cprintf("°°°°°°");
  gotoxy(25,14);
  cprintf("תTEXTתתת");
  gotoxy(34,14);
  cprintf("±±±±±±");
  gotoxy(41,14);
  cprintf("תIMAGEת");
  gotoxy(49,14);
  cprintf("²²²²²²");
  gotoxy(56,14);
  cprintf("תPROCESSORתתש           ");
  gotoxy(2,15);
  cprintf("        שתתתתתת");
  gotoxy(25,15);
  cprintf("תתתתתתתת");
  gotoxy(41,15);
  cprintf("תתתתתתת");
  gotoxy(56,15);
  cprintf("תתתתתתתתתתתתש           ");
  gotoxy(2,16);
  cprintf("        שתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתש           ");
  gotoxy(2,17);
  cprintf("        ששששששששששששששששששששששששששששששששששששששששששששששששששששששששששש           ");
  gotoxy(2,18);
  cprintf("                                                                              ");
  gotoxy(2,19);
  cprintf("                                                                              ");
  gotoxy(2,20);
  cprintf("        FOCHI MICHELE & AMATULLI DAVIDE                                       ");
  gotoxy(2,21);
  cprintf("        VERSIONE 1.0                                                          ");
  gotoxy(2,22);
  cprintf("                                                                              ");
  gotoxy(2,23);
  cprintf("                                                                              ");

  } /* C3 */

