*
* Questo file  stato creato da T.I.P., scritto da Fochi Michele
*

@ 0,0 CLEAR
SET COLOR TO W/N

SET COLOR TO GR+/N
@ 00,00 SAY "ֹֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽ»"
SET COLOR TO GR+/N
@ 01,00 SAY "÷"
SET COLOR TO W+/N
@ 01,01 SAY "                                                                              "
SET COLOR TO GR+/N
@ 01,79 SAY "÷"
SET COLOR TO GR+/N
@ 02,00 SAY "÷"
SET COLOR TO W+/N
@ 02,01 SAY "                                                                              "
SET COLOR TO GR+/N
@ 02,79 SAY "÷"
SET COLOR TO GR+/N
@ 03,00 SAY "÷"
SET COLOR TO W+/N
@ 03,01 SAY "        ששששששששששששששששששששששששששששששששששששששששששששששששששששששששששש           "
SET COLOR TO GR+/N
@ 03,79 SAY "÷"
SET COLOR TO GR+/N
@ 04,00 SAY "÷"
SET COLOR TO W+/N
@ 04,01 SAY "        שתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתש           "
SET COLOR TO GR+/N
@ 04,79 SAY "÷"
SET COLOR TO GR+/N
@ 05,00 SAY "÷"
SET COLOR TO W+/N
@ 05,01 SAY "        שתת"
SET COLOR TO RB+/N
@ 05,12 SAY "Úִִִִִִִִִִִִִִ¿"
SET COLOR TO W+/N
@ 05,28 SAY "תתתת"
SET COLOR TO BG+/N
@ 05,32 SAY "Úִִִִִִ¿"
SET COLOR TO W+/N
@ 05,40 SAY "תתתתתתת"
SET COLOR TO R+/N
@ 05,47 SAY "Úִִִִִִִִִִִִִ¿"
SET COLOR TO W+/N
@ 05,62 SAY "תתתתתש           "
SET COLOR TO GR+/N
@ 05,79 SAY "÷"
SET COLOR TO GR+/N
@ 06,00 SAY "÷"
SET COLOR TO W+/N
@ 06,01 SAY "        שתת"
SET COLOR TO RB+/N
@ 06,12 SAY "³"
SET COLOR TO W+/N
@ 06,13 SAY "°°°°°°°°°°°°°°"
SET COLOR TO RB+/N
@ 06,27 SAY "³"
SET COLOR TO W+/N
@ 06,28 SAY "תתתת"
SET COLOR TO BG+/N
@ 06,32 SAY "³"
SET COLOR TO W+/N
@ 06,33 SAY "±±±±±±"
SET COLOR TO BG+/N
@ 06,39 SAY "³"
SET COLOR TO W+/N
@ 06,40 SAY "תתתתתתת"
SET COLOR TO R+/N
@ 06,47 SAY "³"
SET COLOR TO W+/N
@ 06,48 SAY "²²²²²²²²²²²²²"
SET COLOR TO R+/N
@ 06,61 SAY "ְ¿"
SET COLOR TO W+/N
@ 06,63 SAY "תתתתש           "
SET COLOR TO GR+/N
@ 06,79 SAY "÷"
SET COLOR TO GR+/N
@ 07,00 SAY "÷"
SET COLOR TO W+/N
@ 07,01 SAY "        שתת"
SET COLOR TO RB+/N
@ 07,12 SAY "³"
SET COLOR TO W+/N
@ 07,13 SAY "°°"
SET COLOR TO RB+/N
@ 07,15 SAY "Úִִ¿"
SET COLOR TO W+/N
@ 07,19 SAY "°°"
SET COLOR TO RB+/N
@ 07,21 SAY "Úִִ¿"
SET COLOR TO W+/N
@ 07,25 SAY "°°"
SET COLOR TO RB+/N
@ 07,27 SAY "³"
SET COLOR TO W+/N
@ 07,28 SAY "תתתת"
SET COLOR TO BG+/N
@ 07,32 SAY "ְִ¿"
SET COLOR TO W+/N
@ 07,35 SAY "±±"
SET COLOR TO BG+/N
@ 07,37 SAY "ÚִÙ"
SET COLOR TO W+/N
@ 07,40 SAY "תתתתתתת"
SET COLOR TO R+/N
@ 07,47 SAY "ְִ¿"
SET COLOR TO W+/N
@ 07,50 SAY "²²Úִִִִִִ¿²²"
SET COLOR TO R+/N
@ 07,62 SAY "ְ¿"
SET COLOR TO W+/N
@ 07,64 SAY "תתתש           "
SET COLOR TO GR+/N
@ 07,79 SAY "÷"
SET COLOR TO GR+/N
@ 08,00 SAY "÷"
SET COLOR TO W+/N
@ 08,01 SAY "        שתת"
SET COLOR TO RB+/N
@ 08,12 SAY "ְִִÙ"
SET COLOR TO W+/N
@ 08,16 SAY "תת"
SET COLOR TO RB+/N
@ 08,18 SAY "³"
SET COLOR TO W+/N
@ 08,19 SAY "°°"
SET COLOR TO RB+/N
@ 08,21 SAY "³"
SET COLOR TO W+/N
@ 08,22 SAY "תת"
SET COLOR TO RB+/N
@ 08,24 SAY "ְִִÙ"
SET COLOR TO W+/N
@ 08,28 SAY "תתתתתת"
SET COLOR TO BG+/N
@ 08,34 SAY "³"
SET COLOR TO W+/N
@ 08,35 SAY "±±"
SET COLOR TO BG+/N
@ 08,37 SAY "³"
SET COLOR TO W+/N
@ 08,38 SAY "תתתתתתתתתתת"
SET COLOR TO R+/N
@ 08,49 SAY "³"
SET COLOR TO W+/N
@ 08,50 SAY "²²³תתתתתתֶ ²²"
SET COLOR TO R+/N
@ 08,63 SAY "³"
SET COLOR TO W+/N
@ 08,64 SAY "תתתש           "
SET COLOR TO GR+/N
@ 08,79 SAY "÷"
SET COLOR TO GR+/N
@ 09,00 SAY "÷"
SET COLOR TO W+/N
@ 09,01 SAY "        שתתתתתתתת"
SET COLOR TO RB+/N
@ 09,18 SAY "³"
SET COLOR TO W+/N
@ 09,19 SAY "°°"
SET COLOR TO RB+/N
@ 09,21 SAY "³"
SET COLOR TO W+/N
@ 09,22 SAY "תתתתתתתתתתתת"
SET COLOR TO BG+/N
@ 09,34 SAY "³"
SET COLOR TO W+/N
@ 09,35 SAY "±±"
SET COLOR TO BG+/N
@ 09,37 SAY "³"
SET COLOR TO W+/N
@ 09,38 SAY "תתתתתתתתתתת"
SET COLOR TO R+/N
@ 09,49 SAY "³"
SET COLOR TO W+/N
@ 09,50 SAY "²²ְִִִִִִÙ²²"
SET COLOR TO R+/N
@ 09,62 SAY "ÚÙ"
SET COLOR TO W+/N
@ 09,64 SAY "תתתש           "
SET COLOR TO GR+/N
@ 09,79 SAY "÷"
SET COLOR TO GR+/N
@ 10,00 SAY "÷"
SET COLOR TO W+/N
@ 10,01 SAY "        שתתתתתתתת"
SET COLOR TO RB+/N
@ 10,18 SAY "³"
SET COLOR TO W+/N
@ 10,19 SAY "°°"
SET COLOR TO RB+/N
@ 10,21 SAY "³"
SET COLOR TO W+/N
@ 10,22 SAY "תתתתתתתתתתתת"
SET COLOR TO BG+/N
@ 10,34 SAY "³"
SET COLOR TO W+/N
@ 10,35 SAY "±±"
SET COLOR TO BG+/N
@ 10,37 SAY "³"
SET COLOR TO W+/N
@ 10,38 SAY "תתתתתתתתתתת"
SET COLOR TO R+/N
@ 10,49 SAY "³"
SET COLOR TO W+/N
@ 10,50 SAY "²²²²²²²²²²²"
SET COLOR TO R+/N
@ 10,61 SAY "ÚÙ"
SET COLOR TO W+/N
@ 10,63 SAY "תתתתש           "
SET COLOR TO GR+/N
@ 10,79 SAY "÷"
SET COLOR TO GR+/N
@ 11,00 SAY "÷"
SET COLOR TO W+/N
@ 11,01 SAY "        שתתתתתתתת"
SET COLOR TO RB+/N
@ 11,18 SAY "³"
SET COLOR TO W+/N
@ 11,19 SAY "°°"
SET COLOR TO RB+/N
@ 11,21 SAY "³"
SET COLOR TO W+/N
@ 11,22 SAY "תתתתתתתתתתתת"
SET COLOR TO BG+/N
@ 11,34 SAY "³"
SET COLOR TO W+/N
@ 11,35 SAY "±±"
SET COLOR TO BG+/N
@ 11,37 SAY "³"
SET COLOR TO W+/N
@ 11,38 SAY "תתתתתתתתתתת"
SET COLOR TO R+/N
@ 11,49 SAY "³"
SET COLOR TO W+/N
@ 11,50 SAY "²²"
SET COLOR TO R+/N
@ 11,52 SAY "ÚִִִִִִִִÙ"
SET COLOR TO W+/N
@ 11,62 SAY "תתתתתש           "
SET COLOR TO GR+/N
@ 11,79 SAY "÷"
SET COLOR TO GR+/N
@ 12,00 SAY "÷"
SET COLOR TO W+/N
@ 12,01 SAY "        שתתתתתת"
SET COLOR TO RB+/N
@ 12,16 SAY "ÚִÙ"
SET COLOR TO W+/N
@ 12,19 SAY "°°"
SET COLOR TO RB+/N
@ 12,21 SAY "ְִ¿"
SET COLOR TO W+/N
@ 12,24 SAY "תתתתתתתת"
SET COLOR TO BG+/N
@ 12,32 SAY "ÚִÙ"
SET COLOR TO W+/N
@ 12,35 SAY "±±"
SET COLOR TO BG+/N
@ 12,37 SAY "ְִ¿"
SET COLOR TO W+/N
@ 12,40 SAY "תתתתתתת"
SET COLOR TO R+/N
@ 12,47 SAY "ÚִÙ"
SET COLOR TO W+/N
@ 12,50 SAY "²²"
SET COLOR TO R+/N
@ 12,52 SAY "ְִ¿"
SET COLOR TO W+/N
@ 12,55 SAY "תתתתתתתתתתתתש           "
SET COLOR TO GR+/N
@ 12,79 SAY "÷"
SET COLOR TO GR+/N
@ 13,00 SAY "÷"
SET COLOR TO W+/N
@ 13,01 SAY "        שתתתתתת"
SET COLOR TO RB+/N
@ 13,16 SAY "³"
SET COLOR TO W+/N
@ 13,17 SAY "°°°°°°"
SET COLOR TO RB+/N
@ 13,23 SAY "³"
SET COLOR TO W+/N
@ 13,24 SAY "תTEXTתתת"
SET COLOR TO BG+/N
@ 13,32 SAY "³"
SET COLOR TO W+/N
@ 13,33 SAY "±±±±±±"
SET COLOR TO BG+/N
@ 13,39 SAY "³"
SET COLOR TO W+/N
@ 13,40 SAY "תIMAGEת"
SET COLOR TO R+/N
@ 13,47 SAY "³"
SET COLOR TO W+/N
@ 13,48 SAY "²²²²²²"
SET COLOR TO R+/N
@ 13,54 SAY "³"
SET COLOR TO W+/N
@ 13,55 SAY "תPROCESSORתתש           "
SET COLOR TO GR+/N
@ 13,79 SAY "÷"
SET COLOR TO GR+/N
@ 14,00 SAY "÷"
SET COLOR TO W+/N
@ 14,01 SAY "        שתתתתתת"
SET COLOR TO RB+/N
@ 14,16 SAY "ְִִִִִִÙ"
SET COLOR TO W+/N
@ 14,24 SAY "תתתתתתתת"
SET COLOR TO BG+/N
@ 14,32 SAY "ְִִִִִִÙ"
SET COLOR TO W+/N
@ 14,40 SAY "תתתתתתת"
SET COLOR TO R+/N
@ 14,47 SAY "ְִִִִִִÙ"
SET COLOR TO W+/N
@ 14,55 SAY "תתתתתתתתתתתתש           "
SET COLOR TO GR+/N
@ 14,79 SAY "÷"
SET COLOR TO GR+/N
@ 15,00 SAY "÷"
SET COLOR TO W+/N
@ 15,01 SAY "        שתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתש           "
SET COLOR TO GR+/N
@ 15,79 SAY "÷"
SET COLOR TO GR+/N
@ 16,00 SAY "÷"
SET COLOR TO W+/N
@ 16,01 SAY "        ששששששששששששששששששששששששששששששששששששששששששששששששששששששששששש           "
SET COLOR TO GR+/N
@ 16,79 SAY "÷"
SET COLOR TO GR+/N
@ 17,00 SAY "÷"
SET COLOR TO W+/N
@ 17,01 SAY "                                                                              "
SET COLOR TO GR+/N
@ 17,79 SAY "÷"
SET COLOR TO GR+/N
@ 18,00 SAY "÷"
SET COLOR TO W+/N
@ 18,01 SAY "                                                                              "
SET COLOR TO GR+/N
@ 18,79 SAY "÷"
SET COLOR TO GR+/N
@ 19,00 SAY "÷"
SET COLOR TO W+/N
@ 19,01 SAY "        FOCHI MICHELE & AMATULLI DAVIDE                                       "
SET COLOR TO GR+/N
@ 19,79 SAY "÷"
SET COLOR TO GR+/N
@ 20,00 SAY "÷"
SET COLOR TO W+/N
@ 20,01 SAY "        VERSIONE 1.0                                                          "
SET COLOR TO GR+/N
@ 20,79 SAY "÷"
SET COLOR TO GR+/N
@ 21,00 SAY "÷"
SET COLOR TO W+/N
@ 21,01 SAY "                                                                              "
SET COLOR TO GR+/N
@ 21,79 SAY "÷"
SET COLOR TO GR+/N
@ 22,00 SAY "÷"
SET COLOR TO W+/N
@ 22,01 SAY "                                                                              "
SET COLOR TO GR+/N
@ 22,79 SAY "÷"
SET COLOR TO GR+/N
@ 23,00 SAY "ָֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽ¼"
*
* Fine del programma
*
