{                                                                }
{ Questo file  stato creato da T.I.P., scritto da Fochi Michele }
{                                                                }
{                                                                }
{ La procedura "ClrScr" e le costanti "TextAttr" e "LightGray"   }
{ sono nella unit CRT.TPU.                                       }
{ La procedura "WriteStr"  nella unit VIDEO.TPU.                }
{                                                                }
{ Per eseguire il programma occorre quindi la seguente linea     }
{ di codice (nelle prime righe del programma):                   }
{                                                                }
{     Uses Crt,Video;                                            }

Procedure P4;

Begin { P4 }

{ Cancello lo schermo }
TextAttr := LightGray;
ClrScr;

{ Ora viene riempito lo schermo }

WriteStr(01,01,'ֹֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽ»',014);
WriteStr(01,02,'÷',014);
WriteStr(02,02,'                                                                              ',015);
WriteStr(80,02,'÷',014);
WriteStr(01,03,'÷',014);
WriteStr(02,03,'                                                                              ',015);
WriteStr(80,03,'÷',014);
WriteStr(01,04,'÷',014);
WriteStr(02,04,'        ששששששששששששששששששששששששששששששששששששששששששששששששששששששששששש           ',015);
WriteStr(80,04,'÷',014);
WriteStr(01,05,'÷',014);
WriteStr(02,05,'        שתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתש           ',015);
WriteStr(80,05,'÷',014);
WriteStr(01,06,'÷',014);
WriteStr(02,06,'        שתת',015);
WriteStr(13,06,'Úִִִִִִִִִִִִִִ¿',013);
WriteStr(29,06,'תתתת',015);
WriteStr(33,06,'Úִִִִִִ¿',011);
WriteStr(41,06,'תתתתתתת',015);
WriteStr(48,06,'Úִִִִִִִִִִִִִ¿',012);
WriteStr(63,06,'תתתתתש           ',015);
WriteStr(80,06,'÷',014);
WriteStr(01,07,'÷',014);
WriteStr(02,07,'        שתת',015);
WriteStr(13,07,'³',013);
WriteStr(14,07,'°°°°°°°°°°°°°°',015);
WriteStr(28,07,'³',013);
WriteStr(29,07,'תתתת',015);
WriteStr(33,07,'³',011);
WriteStr(34,07,'±±±±±±',015);
WriteStr(40,07,'³',011);
WriteStr(41,07,'תתתתתתת',015);
WriteStr(48,07,'³',012);
WriteStr(49,07,'²²²²²²²²²²²²²',015);
WriteStr(62,07,'ְ¿',012);
WriteStr(64,07,'תתתתש           ',015);
WriteStr(80,07,'÷',014);
WriteStr(01,08,'÷',014);
WriteStr(02,08,'        שתת',015);
WriteStr(13,08,'³',013);
WriteStr(14,08,'°°',015);
WriteStr(16,08,'Úִִ¿',013);
WriteStr(20,08,'°°',015);
WriteStr(22,08,'Úִִ¿',013);
WriteStr(26,08,'°°',015);
WriteStr(28,08,'³',013);
WriteStr(29,08,'תתתת',015);
WriteStr(33,08,'ְִ¿',011);
WriteStr(36,08,'±±',015);
WriteStr(38,08,'ÚִÙ',011);
WriteStr(41,08,'תתתתתתת',015);
WriteStr(48,08,'ְִ¿',012);
WriteStr(51,08,'²²Úִִִִִִ¿²²',015);
WriteStr(63,08,'ְ¿',012);
WriteStr(65,08,'תתתש           ',015);
WriteStr(80,08,'÷',014);
WriteStr(01,09,'÷',014);
WriteStr(02,09,'        שתת',015);
WriteStr(13,09,'ְִִÙ',013);
WriteStr(17,09,'תת',015);
WriteStr(19,09,'³',013);
WriteStr(20,09,'°°',015);
WriteStr(22,09,'³',013);
WriteStr(23,09,'תת',015);
WriteStr(25,09,'ְִִÙ',013);
WriteStr(29,09,'תתתתתת',015);
WriteStr(35,09,'³',011);
WriteStr(36,09,'±±',015);
WriteStr(38,09,'³',011);
WriteStr(39,09,'תתתתתתתתתתת',015);
WriteStr(50,09,'³',012);
WriteStr(51,09,'²²³תתתתתתֶ ²²',015);
WriteStr(64,09,'³',012);
WriteStr(65,09,'תתתש           ',015);
WriteStr(80,09,'÷',014);
WriteStr(01,10,'÷',014);
WriteStr(02,10,'        שתתתתתתתת',015);
WriteStr(19,10,'³',013);
WriteStr(20,10,'°°',015);
WriteStr(22,10,'³',013);
WriteStr(23,10,'תתתתתתתתתתתת',015);
WriteStr(35,10,'³',011);
WriteStr(36,10,'±±',015);
WriteStr(38,10,'³',011);
WriteStr(39,10,'תתתתתתתתתתת',015);
WriteStr(50,10,'³',012);
WriteStr(51,10,'²²ְִִִִִִÙ²²',015);
WriteStr(63,10,'ÚÙ',012);
WriteStr(65,10,'תתתש           ',015);
WriteStr(80,10,'÷',014);
WriteStr(01,11,'÷',014);
WriteStr(02,11,'        שתתתתתתתת',015);
WriteStr(19,11,'³',013);
WriteStr(20,11,'°°',015);
WriteStr(22,11,'³',013);
WriteStr(23,11,'תתתתתתתתתתתת',015);
WriteStr(35,11,'³',011);
WriteStr(36,11,'±±',015);
WriteStr(38,11,'³',011);
WriteStr(39,11,'תתתתתתתתתתת',015);
WriteStr(50,11,'³',012);
WriteStr(51,11,'²²²²²²²²²²²',015);
WriteStr(62,11,'ÚÙ',012);
WriteStr(64,11,'תתתתש           ',015);
WriteStr(80,11,'÷',014);
WriteStr(01,12,'÷',014);
WriteStr(02,12,'        שתתתתתתתת',015);
WriteStr(19,12,'³',013);
WriteStr(20,12,'°°',015);
WriteStr(22,12,'³',013);
WriteStr(23,12,'תתתתתתתתתתתת',015);
WriteStr(35,12,'³',011);
WriteStr(36,12,'±±',015);
WriteStr(38,12,'³',011);
WriteStr(39,12,'תתתתתתתתתתת',015);
WriteStr(50,12,'³',012);
WriteStr(51,12,'²²',015);
WriteStr(53,12,'ÚִִִִִִִִÙ',012);
WriteStr(63,12,'תתתתתש           ',015);
WriteStr(80,12,'÷',014);
WriteStr(01,13,'÷',014);
WriteStr(02,13,'        שתתתתתת',015);
WriteStr(17,13,'ÚִÙ',013);
WriteStr(20,13,'°°',015);
WriteStr(22,13,'ְִ¿',013);
WriteStr(25,13,'תתתתתתתת',015);
WriteStr(33,13,'ÚִÙ',011);
WriteStr(36,13,'±±',015);
WriteStr(38,13,'ְִ¿',011);
WriteStr(41,13,'תתתתתתת',015);
WriteStr(48,13,'ÚִÙ',012);
WriteStr(51,13,'²²',015);
WriteStr(53,13,'ְִ¿',012);
WriteStr(56,13,'תתתתתתתתתתתתש           ',015);
WriteStr(80,13,'÷',014);
WriteStr(01,14,'÷',014);
WriteStr(02,14,'        שתתתתתת',015);
WriteStr(17,14,'³',013);
WriteStr(18,14,'°°°°°°',015);
WriteStr(24,14,'³',013);
WriteStr(25,14,'תTEXTתתת',015);
WriteStr(33,14,'³',011);
WriteStr(34,14,'±±±±±±',015);
WriteStr(40,14,'³',011);
WriteStr(41,14,'תIMAGEת',015);
WriteStr(48,14,'³',012);
WriteStr(49,14,'²²²²²²',015);
WriteStr(55,14,'³',012);
WriteStr(56,14,'תPROCESSORתתש           ',015);
WriteStr(80,14,'÷',014);
WriteStr(01,15,'÷',014);
WriteStr(02,15,'        שתתתתתת',015);
WriteStr(17,15,'ְִִִִִִÙ',013);
WriteStr(25,15,'תתתתתתתת',015);
WriteStr(33,15,'ְִִִִִִÙ',011);
WriteStr(41,15,'תתתתתתת',015);
WriteStr(48,15,'ְִִִִִִÙ',012);
WriteStr(56,15,'תתתתתתתתתתתתש           ',015);
WriteStr(80,15,'÷',014);
WriteStr(01,16,'÷',014);
WriteStr(02,16,'        שתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתש           ',015);
WriteStr(80,16,'÷',014);
WriteStr(01,17,'÷',014);
WriteStr(02,17,'        ששששששששששששששששששששששששששששששששששששששששששששששששששששששששששש           ',015);
WriteStr(80,17,'÷',014);
WriteStr(01,18,'÷',014);
WriteStr(02,18,'                                                                              ',015);
WriteStr(80,18,'÷',014);
WriteStr(01,19,'÷',014);
WriteStr(02,19,'                                                                              ',015);
WriteStr(80,19,'÷',014);
WriteStr(01,20,'÷',014);
WriteStr(02,20,'        FOCHI MICHELE & AMATULLI DAVIDE                                       ',015);
WriteStr(80,20,'÷',014);
WriteStr(01,21,'÷',014);
WriteStr(02,21,'        VERSIONE 1.0                                                          ',015);
WriteStr(80,21,'÷',014);
WriteStr(01,22,'÷',014);
WriteStr(02,22,'                                                                              ',015);
WriteStr(80,22,'÷',014);
WriteStr(01,23,'÷',014);
WriteStr(02,23,'                                                                              ',015);
WriteStr(80,23,'÷',014);
WriteStr(01,24,'ָֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽֽ¼',014);

End; { P4 }

