/*                                                                */
/* Questo file è stato creato da T.I.P., scritto da Fochi Michele */
/*                                                                */
/*                                                                */
/* Le procedure "clrscr()", "textattr()", "gotoxy()" e            */
/* "cprintf()" e la costante "LIGHTGRAY" sono nella unit CONIO.H  */
/*                                                                */
/* Per eseguire il programma occorre quindi la seguente linea     */
/* di codice (nelle prime righe del programma):                   */
/*                                                                */
/*     #include <conio.h>                                         */

void C1()

  { /* C1 */

  /* Cancello lo schermo */
  textattr(LIGHTGRAY);
  clrscr();

  /* Ora viene riempito lo schermo */

  gotoxy(1,1);          textattr(14);
  cprintf("╔══════════════════════════════════════════════════════════════════════════════╗");
  gotoxy(1,2);          textattr(14);
  cprintf("║");
  gotoxy(2,2);          textattr(15);
  cprintf("                                                                              ");
  gotoxy(80,2);         textattr(14);
  cprintf("║");
  gotoxy(1,3);          textattr(14);
  cprintf("║");
  gotoxy(2,3);          textattr(15);
  cprintf("                                                                              ");
  gotoxy(80,3);         textattr(14);
  cprintf("║");
  gotoxy(1,4);          textattr(14);
  cprintf("║");
  gotoxy(2,4);          textattr(15);
  cprintf("        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ");
  gotoxy(80,4);         textattr(14);
  cprintf("║");
  gotoxy(1,5);          textattr(14);
  cprintf("║");
  gotoxy(2,5);          textattr(15);
  cprintf("        ∙·························································∙           ");
  gotoxy(80,5);         textattr(14);
  cprintf("║");
  gotoxy(1,6);          textattr(14);
  cprintf("║");
  gotoxy(2,6);          textattr(15);
  cprintf("        ∙··");
  gotoxy(13,6);         textattr(13);
  cprintf("┌──────────────┐");
  gotoxy(29,6);         textattr(15);
  cprintf("····");
  gotoxy(33,6);         textattr(11);
  cprintf("┌──────┐");
  gotoxy(41,6);         textattr(15);
  cprintf("·······");
  gotoxy(48,6);         textattr(12);
  cprintf("┌─────────────┐");
  gotoxy(63,6);         textattr(15);
  cprintf("·····∙           ");
  gotoxy(80,6);         textattr(14);
  cprintf("║");
  gotoxy(1,7);          textattr(14);
  cprintf("║");
  gotoxy(2,7);          textattr(15);
  cprintf("        ∙··");
  gotoxy(13,7);         textattr(13);
  cprintf("│");
  gotoxy(14,7);         textattr(15);
  cprintf("░░░░░░░░░░░░░░");
  gotoxy(28,7);         textattr(13);
  cprintf("│");
  gotoxy(29,7);         textattr(15);
  cprintf("····");
  gotoxy(33,7);         textattr(11);
  cprintf("│");
  gotoxy(34,7);         textattr(15);
  cprintf("▒▒▒▒▒▒");
  gotoxy(40,7);         textattr(11);
  cprintf("│");
  gotoxy(41,7);         textattr(15);
  cprintf("·······");
  gotoxy(48,7);         textattr(12);
  cprintf("│");
  gotoxy(49,7);         textattr(15);
  cprintf("▓▓▓▓▓▓▓▓▓▓▓▓▓");
  gotoxy(62,7);         textattr(12);
  cprintf("└┐");
  gotoxy(64,7);         textattr(15);
  cprintf("····∙           ");
  gotoxy(80,7);         textattr(14);
  cprintf("║");
  gotoxy(1,8);          textattr(14);
  cprintf("║");
  gotoxy(2,8);          textattr(15);
  cprintf("        ∙··");
  gotoxy(13,8);         textattr(13);
  cprintf("│");
  gotoxy(14,8);         textattr(15);
  cprintf("░░");
  gotoxy(16,8);         textattr(13);
  cprintf("┌──┐");
  gotoxy(20,8);         textattr(15);
  cprintf("░░");
  gotoxy(22,8);         textattr(13);
  cprintf("┌──┐");
  gotoxy(26,8);         textattr(15);
  cprintf("░░");
  gotoxy(28,8);         textattr(13);
  cprintf("│");
  gotoxy(29,8);         textattr(15);
  cprintf("····");
  gotoxy(33,8);         textattr(11);
  cprintf("└─┐");
  gotoxy(36,8);         textattr(15);
  cprintf("▒▒");
  gotoxy(38,8);         textattr(11);
  cprintf("┌─┘");
  gotoxy(41,8);         textattr(15);
  cprintf("·······");
  gotoxy(48,8);         textattr(12);
  cprintf("└─┐");
  gotoxy(51,8);         textattr(15);
  cprintf("▓▓┌──────┐▓▓");
  gotoxy(63,8);         textattr(12);
  cprintf("└┐");
  gotoxy(65,8);         textattr(15);
  cprintf("···∙           ");
  gotoxy(80,8);         textattr(14);
  cprintf("║");
  gotoxy(1,9);          textattr(14);
  cprintf("║");
  gotoxy(2,9);          textattr(15);
  cprintf("        ∙··");
  gotoxy(13,9);         textattr(13);
  cprintf("└──┘");
  gotoxy(17,9);         textattr(15);
  cprintf("··");
  gotoxy(19,9);         textattr(13);
  cprintf("│");
  gotoxy(20,9);         textattr(15);
  cprintf("░░");
  gotoxy(22,9);         textattr(13);
  cprintf("│");
  gotoxy(23,9);         textattr(15);
  cprintf("··");
  gotoxy(25,9);         textattr(13);
  cprintf("└──┘");
  gotoxy(29,9);         textattr(15);
  cprintf("······");
  gotoxy(35,9);         textattr(11);
  cprintf("│");
  gotoxy(36,9);         textattr(15);
  cprintf("▒▒");
  gotoxy(38,9);         textattr(11);
  cprintf("│");
  gotoxy(39,9);         textattr(15);
  cprintf("···········");
  gotoxy(50,9);         textattr(12);
  cprintf("│");
  gotoxy(51,9);         textattr(15);
  cprintf("▓▓│······╞ ▓▓");
  gotoxy(64,9);         textattr(12);
  cprintf("│");
  gotoxy(65,9);         textattr(15);
  cprintf("···∙           ");
  gotoxy(80,9);         textattr(14);
  cprintf("║");
  gotoxy(1,10);         textattr(14);
  cprintf("║");
  gotoxy(2,10);         textattr(15);
  cprintf("        ∙········");
  gotoxy(19,10);        textattr(13);
  cprintf("│");
  gotoxy(20,10);        textattr(15);
  cprintf("░░");
  gotoxy(22,10);        textattr(13);
  cprintf("│");
  gotoxy(23,10);        textattr(15);
  cprintf("············");
  gotoxy(35,10);        textattr(11);
  cprintf("│");
  gotoxy(36,10);        textattr(15);
  cprintf("▒▒");
  gotoxy(38,10);        textattr(11);
  cprintf("│");
  gotoxy(39,10);        textattr(15);
  cprintf("···········");
  gotoxy(50,10);        textattr(12);
  cprintf("│");
  gotoxy(51,10);        textattr(15);
  cprintf("▓▓└──────┘▓▓");
  gotoxy(63,10);        textattr(12);
  cprintf("┌┘");
  gotoxy(65,10);        textattr(15);
  cprintf("···∙           ");
  gotoxy(80,10);        textattr(14);
  cprintf("║");
  gotoxy(1,11);         textattr(14);
  cprintf("║");
  gotoxy(2,11);         textattr(15);
  cprintf("        ∙········");
  gotoxy(19,11);        textattr(13);
  cprintf("│");
  gotoxy(20,11);        textattr(15);
  cprintf("░░");
  gotoxy(22,11);        textattr(13);
  cprintf("│");
  gotoxy(23,11);        textattr(15);
  cprintf("············");
  gotoxy(35,11);        textattr(11);
  cprintf("│");
  gotoxy(36,11);        textattr(15);
  cprintf("▒▒");
  gotoxy(38,11);        textattr(11);
  cprintf("│");
  gotoxy(39,11);        textattr(15);
  cprintf("···········");
  gotoxy(50,11);        textattr(12);
  cprintf("│");
  gotoxy(51,11);        textattr(15);
  cprintf("▓▓▓▓▓▓▓▓▓▓▓");
  gotoxy(62,11);        textattr(12);
  cprintf("┌┘");
  gotoxy(64,11);        textattr(15);
  cprintf("····∙           ");
  gotoxy(80,11);        textattr(14);
  cprintf("║");
  gotoxy(1,12);         textattr(14);
  cprintf("║");
  gotoxy(2,12);         textattr(15);
  cprintf("        ∙········");
  gotoxy(19,12);        textattr(13);
  cprintf("│");
  gotoxy(20,12);        textattr(15);
  cprintf("░░");
  gotoxy(22,12);        textattr(13);
  cprintf("│");
  gotoxy(23,12);        textattr(15);
  cprintf("············");
  gotoxy(35,12);        textattr(11);
  cprintf("│");
  gotoxy(36,12);        textattr(15);
  cprintf("▒▒");
  gotoxy(38,12);        textattr(11);
  cprintf("│");
  gotoxy(39,12);        textattr(15);
  cprintf("···········");
  gotoxy(50,12);        textattr(12);
  cprintf("│");
  gotoxy(51,12);        textattr(15);
  cprintf("▓▓");
  gotoxy(53,12);        textattr(12);
  cprintf("┌────────┘");
  gotoxy(63,12);        textattr(15);
  cprintf("·····∙           ");
  gotoxy(80,12);        textattr(14);
  cprintf("║");
  gotoxy(1,13);         textattr(14);
  cprintf("║");
  gotoxy(2,13);         textattr(15);
  cprintf("        ∙······");
  gotoxy(17,13);        textattr(13);
  cprintf("┌─┘");
  gotoxy(20,13);        textattr(15);
  cprintf("░░");
  gotoxy(22,13);        textattr(13);
  cprintf("└─┐");
  gotoxy(25,13);        textattr(15);
  cprintf("········");
  gotoxy(33,13);        textattr(11);
  cprintf("┌─┘");
  gotoxy(36,13);        textattr(15);
  cprintf("▒▒");
  gotoxy(38,13);        textattr(11);
  cprintf("└─┐");
  gotoxy(41,13);        textattr(15);
  cprintf("·······");
  gotoxy(48,13);        textattr(12);
  cprintf("┌─┘");
  gotoxy(51,13);        textattr(15);
  cprintf("▓▓");
  gotoxy(53,13);        textattr(12);
  cprintf("└─┐");
  gotoxy(56,13);        textattr(15);
  cprintf("············∙           ");
  gotoxy(80,13);        textattr(14);
  cprintf("║");
  gotoxy(1,14);         textattr(14);
  cprintf("║");
  gotoxy(2,14);         textattr(15);
  cprintf("        ∙······");
  gotoxy(17,14);        textattr(13);
  cprintf("│");
  gotoxy(18,14);        textattr(15);
  cprintf("░░░░░░");
  gotoxy(24,14);        textattr(13);
  cprintf("│");
  gotoxy(25,14);        textattr(15);
  cprintf("·TEXT···");
  gotoxy(33,14);        textattr(11);
  cprintf("│");
  gotoxy(34,14);        textattr(15);
  cprintf("▒▒▒▒▒▒");
  gotoxy(40,14);        textattr(11);
  cprintf("│");
  gotoxy(41,14);        textattr(15);
  cprintf("·IMAGE·");
  gotoxy(48,14);        textattr(12);
  cprintf("│");
  gotoxy(49,14);        textattr(15);
  cprintf("▓▓▓▓▓▓");
  gotoxy(55,14);        textattr(12);
  cprintf("│");
  gotoxy(56,14);        textattr(15);
  cprintf("·PROCESSOR··∙           ");
  gotoxy(80,14);        textattr(14);
  cprintf("║");
  gotoxy(1,15);         textattr(14);
  cprintf("║");
  gotoxy(2,15);         textattr(15);
  cprintf("        ∙······");
  gotoxy(17,15);        textattr(13);
  cprintf("└──────┘");
  gotoxy(25,15);        textattr(15);
  cprintf("········");
  gotoxy(33,15);        textattr(11);
  cprintf("└──────┘");
  gotoxy(41,15);        textattr(15);
  cprintf("·······");
  gotoxy(48,15);        textattr(12);
  cprintf("└──────┘");
  gotoxy(56,15);        textattr(15);
  cprintf("············∙           ");
  gotoxy(80,15);        textattr(14);
  cprintf("║");
  gotoxy(1,16);         textattr(14);
  cprintf("║");
  gotoxy(2,16);         textattr(15);
  cprintf("        ∙·························································∙           ");
  gotoxy(80,16);        textattr(14);
  cprintf("║");
  gotoxy(1,17);         textattr(14);
  cprintf("║");
  gotoxy(2,17);         textattr(15);
  cprintf("        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ");
  gotoxy(80,17);        textattr(14);
  cprintf("║");
  gotoxy(1,18);         textattr(14);
  cprintf("║");
  gotoxy(2,18);         textattr(15);
  cprintf("                                                                              ");
  gotoxy(80,18);        textattr(14);
  cprintf("║");
  gotoxy(1,19);         textattr(14);
  cprintf("║");
  gotoxy(2,19);         textattr(15);
  cprintf("                                                                              ");
  gotoxy(80,19);        textattr(14);
  cprintf("║");
  gotoxy(1,20);         textattr(14);
  cprintf("║");
  gotoxy(2,20);         textattr(15);
  cprintf("        FOCHI MICHELE & AMATULLI DAVIDE                                       ");
  gotoxy(80,20);        textattr(14);
  cprintf("║");
  gotoxy(1,21);         textattr(14);
  cprintf("║");
  gotoxy(2,21);         textattr(15);
  cprintf("        VERSIONE 1.0                                                          ");
  gotoxy(80,21);        textattr(14);
  cprintf("║");
  gotoxy(1,22);         textattr(14);
  cprintf("║");
  gotoxy(2,22);         textattr(15);
  cprintf("                                                                              ");
  gotoxy(80,22);        textattr(14);
  cprintf("║");
  gotoxy(1,23);         textattr(14);
  cprintf("║");
  gotoxy(2,23);         textattr(15);
  cprintf("                                                                              ");
  gotoxy(80,23);        textattr(14);
  cprintf("║");
  gotoxy(1,24);         textattr(14);
  cprintf("╚══════════════════════════════════════════════════════════════════════════════╝");

  } /* C1 */

