/*                                                                */
/* Questo file è stato creato da T.I.P., scritto da Fochi Michele */
/*                                                                */
/*                                                                */
/* Le procedure "clrscr()", "textattr()", "gotoxy()" e            */
/* "cprintf()" e la costante "LIGHTGRAY" sono nella unit CONIO.H  */
/*                                                                */
/* Per eseguire il programma occorre quindi la seguente linea     */
/* di codice (nelle prime righe del programma):                   */
/*                                                                */
/*     #include <conio.h>                                         */

void C2()

  { /* C2 */

  /* Cancello lo schermo */
  textattr(LIGHTGRAY);
  clrscr();

  /* Ora viene riempito lo schermo */

  textattr(14);
  cprintf("╔══════════════════════════════════════════════════════════════════════════════╗");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙·························································∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙··");
  textattr(13);
  cprintf("┌──────────────┐");
  textattr(15);
  cprintf("····");
  textattr(11);
  cprintf("┌──────┐");
  textattr(15);
  cprintf("·······");
  textattr(12);
  cprintf("┌─────────────┐");
  textattr(15);
  cprintf("·····∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙··");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("░░░░░░░░░░░░░░");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("····");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("▒▒▒▒▒▒");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("·······");
  textattr(12);
  cprintf("│");
  textattr(15);
  cprintf("▓▓▓▓▓▓▓▓▓▓▓▓▓");
  textattr(12);
  cprintf("└┐");
  textattr(15);
  cprintf("····∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙··");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("░░");
  textattr(13);
  cprintf("┌──┐");
  textattr(15);
  cprintf("░░");
  textattr(13);
  cprintf("┌──┐");
  textattr(15);
  cprintf("░░");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("····");
  textattr(11);
  cprintf("└─┐");
  textattr(15);
  cprintf("▒▒");
  textattr(11);
  cprintf("┌─┘");
  textattr(15);
  cprintf("·······");
  textattr(12);
  cprintf("└─┐");
  textattr(15);
  cprintf("▓▓┌──────┐▓▓");
  textattr(12);
  cprintf("└┐");
  textattr(15);
  cprintf("···∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙··");
  textattr(13);
  cprintf("└──┘");
  textattr(15);
  cprintf("··");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("░░");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("··");
  textattr(13);
  cprintf("└──┘");
  textattr(15);
  cprintf("······");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("▒▒");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("···········");
  textattr(12);
  cprintf("│");
  textattr(15);
  cprintf("▓▓│······╞ ▓▓");
  textattr(12);
  cprintf("│");
  textattr(15);
  cprintf("···∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙········");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("░░");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("············");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("▒▒");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("···········");
  textattr(12);
  cprintf("│");
  textattr(15);
  cprintf("▓▓└──────┘▓▓");
  textattr(12);
  cprintf("┌┘");
  textattr(15);
  cprintf("···∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙········");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("░░");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("············");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("▒▒");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("···········");
  textattr(12);
  cprintf("│");
  textattr(15);
  cprintf("▓▓▓▓▓▓▓▓▓▓▓");
  textattr(12);
  cprintf("┌┘");
  textattr(15);
  cprintf("····∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙········");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("░░");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("············");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("▒▒");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("···········");
  textattr(12);
  cprintf("│");
  textattr(15);
  cprintf("▓▓");
  textattr(12);
  cprintf("┌────────┘");
  textattr(15);
  cprintf("·····∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙······");
  textattr(13);
  cprintf("┌─┘");
  textattr(15);
  cprintf("░░");
  textattr(13);
  cprintf("└─┐");
  textattr(15);
  cprintf("········");
  textattr(11);
  cprintf("┌─┘");
  textattr(15);
  cprintf("▒▒");
  textattr(11);
  cprintf("└─┐");
  textattr(15);
  cprintf("·······");
  textattr(12);
  cprintf("┌─┘");
  textattr(15);
  cprintf("▓▓");
  textattr(12);
  cprintf("└─┐");
  textattr(15);
  cprintf("············∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙······");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("░░░░░░");
  textattr(13);
  cprintf("│");
  textattr(15);
  cprintf("·TEXT···");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("▒▒▒▒▒▒");
  textattr(11);
  cprintf("│");
  textattr(15);
  cprintf("·IMAGE·");
  textattr(12);
  cprintf("│");
  textattr(15);
  cprintf("▓▓▓▓▓▓");
  textattr(12);
  cprintf("│");
  textattr(15);
  cprintf("·PROCESSOR··∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙······");
  textattr(13);
  cprintf("└──────┘");
  textattr(15);
  cprintf("········");
  textattr(11);
  cprintf("└──────┘");
  textattr(15);
  cprintf("·······");
  textattr(12);
  cprintf("└──────┘");
  textattr(15);
  cprintf("············∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙·························································∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        FOCHI MICHELE & AMATULLI DAVIDE                                       ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("        VERSIONE 1.0                                                          ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("║");
  textattr(15);
  cprintf("                                                                              ");
  textattr(14);
  cprintf("║");
  textattr(14);
  cprintf("╚══════════════════════════════════════════════════════════════════════════════╝");

  } /* C2 */

