/*                                                                */
/* Questo file è stato creato da T.I.P., scritto da Fochi Michele */
/*                                                                */
/*                                                                */
/* Le procedure "clrscr()", "textattr()", "gotoxy()" e            */
/* "cprintf()" e la costante "LIGHTGRAY" sono nella unit CONIO.H  */
/*                                                                */
/* Per eseguire il programma occorre quindi la seguente linea     */
/* di codice (nelle prime righe del programma):                   */
/*                                                                */
/*     #include <conio.h>                                         */

void C3()

  { /* C3 */

  /* Cancello lo schermo */
  textattr(LIGHTGRAY);
  clrscr();

  /* Ora viene riempito lo schermo */


  textattr(11);
  gotoxy(33,6);
  cprintf("┌──────┐");
  gotoxy(33,7);
  cprintf("│");
  gotoxy(40,7);
  cprintf("│");
  gotoxy(33,8);
  cprintf("└─┐");
  gotoxy(38,8);
  cprintf("┌─┘");
  gotoxy(35,9);
  cprintf("│");
  gotoxy(38,9);
  cprintf("│");
  gotoxy(35,10);
  cprintf("│");
  gotoxy(38,10);
  cprintf("│");
  gotoxy(35,11);
  cprintf("│");
  gotoxy(38,11);
  cprintf("│");
  gotoxy(35,12);
  cprintf("│");
  gotoxy(38,12);
  cprintf("│");
  gotoxy(33,13);
  cprintf("┌─┘");
  gotoxy(38,13);
  cprintf("└─┐");
  gotoxy(33,14);
  cprintf("│");
  gotoxy(40,14);
  cprintf("│");
  gotoxy(33,15);
  cprintf("└──────┘");

  textattr(12);
  gotoxy(48,6);
  cprintf("┌─────────────┐");
  gotoxy(48,7);
  cprintf("│");
  gotoxy(62,7);
  cprintf("└┐");
  gotoxy(48,8);
  cprintf("└─┐");
  gotoxy(63,8);
  cprintf("└┐");
  gotoxy(50,9);
  cprintf("│");
  gotoxy(64,9);
  cprintf("│");
  gotoxy(50,10);
  cprintf("│");
  gotoxy(63,10);
  cprintf("┌┘");
  gotoxy(50,11);
  cprintf("│");
  gotoxy(62,11);
  cprintf("┌┘");
  gotoxy(50,12);
  cprintf("│");
  gotoxy(53,12);
  cprintf("┌────────┘");
  gotoxy(48,13);
  cprintf("┌─┘");
  gotoxy(53,13);
  cprintf("└─┐");
  gotoxy(48,14);
  cprintf("│");
  gotoxy(55,14);
  cprintf("│");
  gotoxy(48,15);
  cprintf("└──────┘");

  textattr(13);
  gotoxy(13,6);
  cprintf("┌──────────────┐");
  gotoxy(13,7);
  cprintf("│");
  gotoxy(28,7);
  cprintf("│");
  gotoxy(13,8);
  cprintf("│");
  gotoxy(16,8);
  cprintf("┌──┐");
  gotoxy(22,8);
  cprintf("┌──┐");
  gotoxy(28,8);
  cprintf("│");
  gotoxy(13,9);
  cprintf("└──┘");
  gotoxy(19,9);
  cprintf("│");
  gotoxy(22,9);
  cprintf("│");
  gotoxy(25,9);
  cprintf("└──┘");
  gotoxy(19,10);
  cprintf("│");
  gotoxy(22,10);
  cprintf("│");
  gotoxy(19,11);
  cprintf("│");
  gotoxy(22,11);
  cprintf("│");
  gotoxy(19,12);
  cprintf("│");
  gotoxy(22,12);
  cprintf("│");
  gotoxy(17,13);
  cprintf("┌─┘");
  gotoxy(22,13);
  cprintf("└─┐");
  gotoxy(17,14);
  cprintf("│");
  gotoxy(24,14);
  cprintf("│");
  gotoxy(17,15);
  cprintf("└──────┘");

  textattr(14);
  gotoxy(1,1);
  cprintf("╔══════════════════════════════════════════════════════════════════════════════╗");
  gotoxy(1,2);
  cprintf("║");
  gotoxy(80,2);
  cprintf("║");
  gotoxy(1,3);
  cprintf("║");
  gotoxy(80,3);
  cprintf("║");
  gotoxy(1,4);
  cprintf("║");
  gotoxy(80,4);
  cprintf("║");
  gotoxy(1,5);
  cprintf("║");
  gotoxy(80,5);
  cprintf("║");
  gotoxy(1,6);
  cprintf("║");
  gotoxy(80,6);
  cprintf("║");
  gotoxy(1,7);
  cprintf("║");
  gotoxy(80,7);
  cprintf("║");
  gotoxy(1,8);
  cprintf("║");
  gotoxy(80,8);
  cprintf("║");
  gotoxy(1,9);
  cprintf("║");
  gotoxy(80,9);
  cprintf("║");
  gotoxy(1,10);
  cprintf("║");
  gotoxy(80,10);
  cprintf("║");
  gotoxy(1,11);
  cprintf("║");
  gotoxy(80,11);
  cprintf("║");
  gotoxy(1,12);
  cprintf("║");
  gotoxy(80,12);
  cprintf("║");
  gotoxy(1,13);
  cprintf("║");
  gotoxy(80,13);
  cprintf("║");
  gotoxy(1,14);
  cprintf("║");
  gotoxy(80,14);
  cprintf("║");
  gotoxy(1,15);
  cprintf("║");
  gotoxy(80,15);
  cprintf("║");
  gotoxy(1,16);
  cprintf("║");
  gotoxy(80,16);
  cprintf("║");
  gotoxy(1,17);
  cprintf("║");
  gotoxy(80,17);
  cprintf("║");
  gotoxy(1,18);
  cprintf("║");
  gotoxy(80,18);
  cprintf("║");
  gotoxy(1,19);
  cprintf("║");
  gotoxy(80,19);
  cprintf("║");
  gotoxy(1,20);
  cprintf("║");
  gotoxy(80,20);
  cprintf("║");
  gotoxy(1,21);
  cprintf("║");
  gotoxy(80,21);
  cprintf("║");
  gotoxy(1,22);
  cprintf("║");
  gotoxy(80,22);
  cprintf("║");
  gotoxy(1,23);
  cprintf("║");
  gotoxy(80,23);
  cprintf("║");
  gotoxy(1,24);
  cprintf("╚══════════════════════════════════════════════════════════════════════════════╝");

  textattr(15);
  gotoxy(2,2);
  cprintf("                                                                              ");
  gotoxy(2,3);
  cprintf("                                                                              ");
  gotoxy(2,4);
  cprintf("        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ");
  gotoxy(2,5);
  cprintf("        ∙·························································∙           ");
  gotoxy(2,6);
  cprintf("        ∙··");
  gotoxy(29,6);
  cprintf("····");
  gotoxy(41,6);
  cprintf("·······");
  gotoxy(63,6);
  cprintf("·····∙           ");
  gotoxy(2,7);
  cprintf("        ∙··");
  gotoxy(14,7);
  cprintf("░░░░░░░░░░░░░░");
  gotoxy(29,7);
  cprintf("····");
  gotoxy(34,7);
  cprintf("▒▒▒▒▒▒");
  gotoxy(41,7);
  cprintf("·······");
  gotoxy(49,7);
  cprintf("▓▓▓▓▓▓▓▓▓▓▓▓▓");
  gotoxy(64,7);
  cprintf("····∙           ");
  gotoxy(2,8);
  cprintf("        ∙··");
  gotoxy(14,8);
  cprintf("░░");
  gotoxy(20,8);
  cprintf("░░");
  gotoxy(26,8);
  cprintf("░░");
  gotoxy(29,8);
  cprintf("····");
  gotoxy(36,8);
  cprintf("▒▒");
  gotoxy(41,8);
  cprintf("·······");
  gotoxy(51,8);
  cprintf("▓▓┌──────┐▓▓");
  gotoxy(65,8);
  cprintf("···∙           ");
  gotoxy(2,9);
  cprintf("        ∙··");
  gotoxy(17,9);
  cprintf("··");
  gotoxy(20,9);
  cprintf("░░");
  gotoxy(23,9);
  cprintf("··");
  gotoxy(29,9);
  cprintf("······");
  gotoxy(36,9);
  cprintf("▒▒");
  gotoxy(39,9);
  cprintf("···········");
  gotoxy(51,9);
  cprintf("▓▓│······╞ ▓▓");
  gotoxy(65,9);
  cprintf("···∙           ");
  gotoxy(2,10);
  cprintf("        ∙········");
  gotoxy(20,10);
  cprintf("░░");
  gotoxy(23,10);
  cprintf("············");
  gotoxy(36,10);
  cprintf("▒▒");
  gotoxy(39,10);
  cprintf("···········");
  gotoxy(51,10);
  cprintf("▓▓└──────┘▓▓");
  gotoxy(65,10);
  cprintf("···∙           ");
  gotoxy(2,11);
  cprintf("        ∙········");
  gotoxy(20,11);
  cprintf("░░");
  gotoxy(23,11);
  cprintf("············");
  gotoxy(36,11);
  cprintf("▒▒");
  gotoxy(39,11);
  cprintf("···········");
  gotoxy(51,11);
  cprintf("▓▓▓▓▓▓▓▓▓▓▓");
  gotoxy(64,11);
  cprintf("····∙           ");
  gotoxy(2,12);
  cprintf("        ∙········");
  gotoxy(20,12);
  cprintf("░░");
  gotoxy(23,12);
  cprintf("············");
  gotoxy(36,12);
  cprintf("▒▒");
  gotoxy(39,12);
  cprintf("···········");
  gotoxy(51,12);
  cprintf("▓▓");
  gotoxy(63,12);
  cprintf("·····∙           ");
  gotoxy(2,13);
  cprintf("        ∙······");
  gotoxy(20,13);
  cprintf("░░");
  gotoxy(25,13);
  cprintf("········");
  gotoxy(36,13);
  cprintf("▒▒");
  gotoxy(41,13);
  cprintf("·······");
  gotoxy(51,13);
  cprintf("▓▓");
  gotoxy(56,13);
  cprintf("············∙           ");
  gotoxy(2,14);
  cprintf("        ∙······");
  gotoxy(18,14);
  cprintf("░░░░░░");
  gotoxy(25,14);
  cprintf("·TEXT···");
  gotoxy(34,14);
  cprintf("▒▒▒▒▒▒");
  gotoxy(41,14);
  cprintf("·IMAGE·");
  gotoxy(49,14);
  cprintf("▓▓▓▓▓▓");
  gotoxy(56,14);
  cprintf("·PROCESSOR··∙           ");
  gotoxy(2,15);
  cprintf("        ∙······");
  gotoxy(25,15);
  cprintf("········");
  gotoxy(41,15);
  cprintf("·······");
  gotoxy(56,15);
  cprintf("············∙           ");
  gotoxy(2,16);
  cprintf("        ∙·························································∙           ");
  gotoxy(2,17);
  cprintf("        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ");
  gotoxy(2,18);
  cprintf("                                                                              ");
  gotoxy(2,19);
  cprintf("                                                                              ");
  gotoxy(2,20);
  cprintf("        FOCHI MICHELE & AMATULLI DAVIDE                                       ");
  gotoxy(2,21);
  cprintf("        VERSIONE 1.0                                                          ");
  gotoxy(2,22);
  cprintf("                                                                              ");
  gotoxy(2,23);
  cprintf("                                                                              ");

  } /* C3 */

