{                                                                }
{ Questo file è stato creato da T.I.P., scritto da Fochi Michele }
{                                                                }
{                                                                }
{ Le procedure "ClrScr", "Write" e "GoToXY", e le costanti       }
{ "TextAttr" e "LightGray" sono nella unit CRT.TPU.              }
{                                                                }
{ Per eseguire il programma occorre quindi la seguente linea     }
{ di codice (nelle prime righe del programma):                   }
{                                                                }
{     Uses Crt;                                                  }

Procedure P2;

Begin { P2 }

{ Cancello lo schermo }
TextAttr := LightGray;
ClrScr;

{ Ora viene riempito lo schermo }

TextAttr := 014;
Write('╔══════════════════════════════════════════════════════════════════════════════╗');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('                                                                              ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('                                                                              ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙·························································∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙··');
TextAttr := 013;
Write('┌──────────────┐');
TextAttr := 015;
Write('····');
TextAttr := 011;
Write('┌──────┐');
TextAttr := 015;
Write('·······');
TextAttr := 012;
Write('┌─────────────┐');
TextAttr := 015;
Write('·····∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙··');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('░░░░░░░░░░░░░░');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('····');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('▒▒▒▒▒▒');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('·······');
TextAttr := 012;
Write('│');
TextAttr := 015;
Write('▓▓▓▓▓▓▓▓▓▓▓▓▓');
TextAttr := 012;
Write('└┐');
TextAttr := 015;
Write('····∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙··');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('░░');
TextAttr := 013;
Write('┌──┐');
TextAttr := 015;
Write('░░');
TextAttr := 013;
Write('┌──┐');
TextAttr := 015;
Write('░░');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('····');
TextAttr := 011;
Write('└─┐');
TextAttr := 015;
Write('▒▒');
TextAttr := 011;
Write('┌─┘');
TextAttr := 015;
Write('·······');
TextAttr := 012;
Write('└─┐');
TextAttr := 015;
Write('▓▓┌──────┐▓▓');
TextAttr := 012;
Write('└┐');
TextAttr := 015;
Write('···∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙··');
TextAttr := 013;
Write('└──┘');
TextAttr := 015;
Write('··');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('░░');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('··');
TextAttr := 013;
Write('└──┘');
TextAttr := 015;
Write('······');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('▒▒');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('···········');
TextAttr := 012;
Write('│');
TextAttr := 015;
Write('▓▓│······╞ ▓▓');
TextAttr := 012;
Write('│');
TextAttr := 015;
Write('···∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙········');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('░░');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('············');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('▒▒');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('···········');
TextAttr := 012;
Write('│');
TextAttr := 015;
Write('▓▓└──────┘▓▓');
TextAttr := 012;
Write('┌┘');
TextAttr := 015;
Write('···∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙········');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('░░');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('············');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('▒▒');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('···········');
TextAttr := 012;
Write('│');
TextAttr := 015;
Write('▓▓▓▓▓▓▓▓▓▓▓');
TextAttr := 012;
Write('┌┘');
TextAttr := 015;
Write('····∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙········');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('░░');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('············');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('▒▒');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('···········');
TextAttr := 012;
Write('│');
TextAttr := 015;
Write('▓▓');
TextAttr := 012;
Write('┌────────┘');
TextAttr := 015;
Write('·····∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙······');
TextAttr := 013;
Write('┌─┘');
TextAttr := 015;
Write('░░');
TextAttr := 013;
Write('└─┐');
TextAttr := 015;
Write('········');
TextAttr := 011;
Write('┌─┘');
TextAttr := 015;
Write('▒▒');
TextAttr := 011;
Write('└─┐');
TextAttr := 015;
Write('·······');
TextAttr := 012;
Write('┌─┘');
TextAttr := 015;
Write('▓▓');
TextAttr := 012;
Write('└─┐');
TextAttr := 015;
Write('············∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙······');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('░░░░░░');
TextAttr := 013;
Write('│');
TextAttr := 015;
Write('·TEXT···');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('▒▒▒▒▒▒');
TextAttr := 011;
Write('│');
TextAttr := 015;
Write('·IMAGE·');
TextAttr := 012;
Write('│');
TextAttr := 015;
Write('▓▓▓▓▓▓');
TextAttr := 012;
Write('│');
TextAttr := 015;
Write('·PROCESSOR··∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙······');
TextAttr := 013;
Write('└──────┘');
TextAttr := 015;
Write('········');
TextAttr := 011;
Write('└──────┘');
TextAttr := 015;
Write('·······');
TextAttr := 012;
Write('└──────┘');
TextAttr := 015;
Write('············∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙·························································∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('                                                                              ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('                                                                              ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        FOCHI MICHELE & AMATULLI DAVIDE                                       ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('        VERSIONE 1.0                                                          ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('                                                                              ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('║');
TextAttr := 015;
Write('                                                                              ');
TextAttr := 014;
Write('║');
TextAttr := 014;
Write('╚══════════════════════════════════════════════════════════════════════════════╝');

End; { P2 }

