{                                                                }
{ Questo file è stato creato da T.I.P., scritto da Fochi Michele }
{                                                                }
{                                                                }
{ Le procedure "ClrScr", "Write" e "GoToXY", e le costanti       }
{ "TextAttr" e "LightGray" sono nella unit CRT.TPU.              }
{                                                                }
{ Per eseguire il programma occorre quindi la seguente linea     }
{ di codice (nelle prime righe del programma):                   }
{                                                                }
{     Uses Crt;                                                  }

Procedure P3;

Begin { P3 }

{ Cancello lo schermo }
TextAttr := LightGray;
ClrScr;

{ Ora viene riempito lo schermo }


TextAttr := 011;
GoToXY(33,06);
Write('┌──────┐');
GoToXY(33,07);
Write('│');
GoToXY(40,07);
Write('│');
GoToXY(33,08);
Write('└─┐');
GoToXY(38,08);
Write('┌─┘');
GoToXY(35,09);
Write('│');
GoToXY(38,09);
Write('│');
GoToXY(35,10);
Write('│');
GoToXY(38,10);
Write('│');
GoToXY(35,11);
Write('│');
GoToXY(38,11);
Write('│');
GoToXY(35,12);
Write('│');
GoToXY(38,12);
Write('│');
GoToXY(33,13);
Write('┌─┘');
GoToXY(38,13);
Write('└─┐');
GoToXY(33,14);
Write('│');
GoToXY(40,14);
Write('│');
GoToXY(33,15);
Write('└──────┘');

TextAttr := 012;
GoToXY(48,06);
Write('┌─────────────┐');
GoToXY(48,07);
Write('│');
GoToXY(62,07);
Write('└┐');
GoToXY(48,08);
Write('└─┐');
GoToXY(63,08);
Write('└┐');
GoToXY(50,09);
Write('│');
GoToXY(64,09);
Write('│');
GoToXY(50,10);
Write('│');
GoToXY(63,10);
Write('┌┘');
GoToXY(50,11);
Write('│');
GoToXY(62,11);
Write('┌┘');
GoToXY(50,12);
Write('│');
GoToXY(53,12);
Write('┌────────┘');
GoToXY(48,13);
Write('┌─┘');
GoToXY(53,13);
Write('└─┐');
GoToXY(48,14);
Write('│');
GoToXY(55,14);
Write('│');
GoToXY(48,15);
Write('└──────┘');

TextAttr := 013;
GoToXY(13,06);
Write('┌──────────────┐');
GoToXY(13,07);
Write('│');
GoToXY(28,07);
Write('│');
GoToXY(13,08);
Write('│');
GoToXY(16,08);
Write('┌──┐');
GoToXY(22,08);
Write('┌──┐');
GoToXY(28,08);
Write('│');
GoToXY(13,09);
Write('└──┘');
GoToXY(19,09);
Write('│');
GoToXY(22,09);
Write('│');
GoToXY(25,09);
Write('└──┘');
GoToXY(19,10);
Write('│');
GoToXY(22,10);
Write('│');
GoToXY(19,11);
Write('│');
GoToXY(22,11);
Write('│');
GoToXY(19,12);
Write('│');
GoToXY(22,12);
Write('│');
GoToXY(17,13);
Write('┌─┘');
GoToXY(22,13);
Write('└─┐');
GoToXY(17,14);
Write('│');
GoToXY(24,14);
Write('│');
GoToXY(17,15);
Write('└──────┘');

TextAttr := 014;
GoToXY(01,01);
Write('╔══════════════════════════════════════════════════════════════════════════════╗');
GoToXY(01,02);
Write('║');
GoToXY(80,02);
Write('║');
GoToXY(01,03);
Write('║');
GoToXY(80,03);
Write('║');
GoToXY(01,04);
Write('║');
GoToXY(80,04);
Write('║');
GoToXY(01,05);
Write('║');
GoToXY(80,05);
Write('║');
GoToXY(01,06);
Write('║');
GoToXY(80,06);
Write('║');
GoToXY(01,07);
Write('║');
GoToXY(80,07);
Write('║');
GoToXY(01,08);
Write('║');
GoToXY(80,08);
Write('║');
GoToXY(01,09);
Write('║');
GoToXY(80,09);
Write('║');
GoToXY(01,10);
Write('║');
GoToXY(80,10);
Write('║');
GoToXY(01,11);
Write('║');
GoToXY(80,11);
Write('║');
GoToXY(01,12);
Write('║');
GoToXY(80,12);
Write('║');
GoToXY(01,13);
Write('║');
GoToXY(80,13);
Write('║');
GoToXY(01,14);
Write('║');
GoToXY(80,14);
Write('║');
GoToXY(01,15);
Write('║');
GoToXY(80,15);
Write('║');
GoToXY(01,16);
Write('║');
GoToXY(80,16);
Write('║');
GoToXY(01,17);
Write('║');
GoToXY(80,17);
Write('║');
GoToXY(01,18);
Write('║');
GoToXY(80,18);
Write('║');
GoToXY(01,19);
Write('║');
GoToXY(80,19);
Write('║');
GoToXY(01,20);
Write('║');
GoToXY(80,20);
Write('║');
GoToXY(01,21);
Write('║');
GoToXY(80,21);
Write('║');
GoToXY(01,22);
Write('║');
GoToXY(80,22);
Write('║');
GoToXY(01,23);
Write('║');
GoToXY(80,23);
Write('║');
GoToXY(01,24);
Write('╚══════════════════════════════════════════════════════════════════════════════╝');

TextAttr := 015;
GoToXY(02,02);
Write('                                                                              ');
GoToXY(02,03);
Write('                                                                              ');
GoToXY(02,04);
Write('        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ');
GoToXY(02,05);
Write('        ∙·························································∙           ');
GoToXY(02,06);
Write('        ∙··');
GoToXY(29,06);
Write('····');
GoToXY(41,06);
Write('·······');
GoToXY(63,06);
Write('·····∙           ');
GoToXY(02,07);
Write('        ∙··');
GoToXY(14,07);
Write('░░░░░░░░░░░░░░');
GoToXY(29,07);
Write('····');
GoToXY(34,07);
Write('▒▒▒▒▒▒');
GoToXY(41,07);
Write('·······');
GoToXY(49,07);
Write('▓▓▓▓▓▓▓▓▓▓▓▓▓');
GoToXY(64,07);
Write('····∙           ');
GoToXY(02,08);
Write('        ∙··');
GoToXY(14,08);
Write('░░');
GoToXY(20,08);
Write('░░');
GoToXY(26,08);
Write('░░');
GoToXY(29,08);
Write('····');
GoToXY(36,08);
Write('▒▒');
GoToXY(41,08);
Write('·······');
GoToXY(51,08);
Write('▓▓┌──────┐▓▓');
GoToXY(65,08);
Write('···∙           ');
GoToXY(02,09);
Write('        ∙··');
GoToXY(17,09);
Write('··');
GoToXY(20,09);
Write('░░');
GoToXY(23,09);
Write('··');
GoToXY(29,09);
Write('······');
GoToXY(36,09);
Write('▒▒');
GoToXY(39,09);
Write('···········');
GoToXY(51,09);
Write('▓▓│······╞ ▓▓');
GoToXY(65,09);
Write('···∙           ');
GoToXY(02,10);
Write('        ∙········');
GoToXY(20,10);
Write('░░');
GoToXY(23,10);
Write('············');
GoToXY(36,10);
Write('▒▒');
GoToXY(39,10);
Write('···········');
GoToXY(51,10);
Write('▓▓└──────┘▓▓');
GoToXY(65,10);
Write('···∙           ');
GoToXY(02,11);
Write('        ∙········');
GoToXY(20,11);
Write('░░');
GoToXY(23,11);
Write('············');
GoToXY(36,11);
Write('▒▒');
GoToXY(39,11);
Write('···········');
GoToXY(51,11);
Write('▓▓▓▓▓▓▓▓▓▓▓');
GoToXY(64,11);
Write('····∙           ');
GoToXY(02,12);
Write('        ∙········');
GoToXY(20,12);
Write('░░');
GoToXY(23,12);
Write('············');
GoToXY(36,12);
Write('▒▒');
GoToXY(39,12);
Write('···········');
GoToXY(51,12);
Write('▓▓');
GoToXY(63,12);
Write('·····∙           ');
GoToXY(02,13);
Write('        ∙······');
GoToXY(20,13);
Write('░░');
GoToXY(25,13);
Write('········');
GoToXY(36,13);
Write('▒▒');
GoToXY(41,13);
Write('·······');
GoToXY(51,13);
Write('▓▓');
GoToXY(56,13);
Write('············∙           ');
GoToXY(02,14);
Write('        ∙······');
GoToXY(18,14);
Write('░░░░░░');
GoToXY(25,14);
Write('·TEXT···');
GoToXY(34,14);
Write('▒▒▒▒▒▒');
GoToXY(41,14);
Write('·IMAGE·');
GoToXY(49,14);
Write('▓▓▓▓▓▓');
GoToXY(56,14);
Write('·PROCESSOR··∙           ');
GoToXY(02,15);
Write('        ∙······');
GoToXY(25,15);
Write('········');
GoToXY(41,15);
Write('·······');
GoToXY(56,15);
Write('············∙           ');
GoToXY(02,16);
Write('        ∙·························································∙           ');
GoToXY(02,17);
Write('        ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙           ');
GoToXY(02,18);
Write('                                                                              ');
GoToXY(02,19);
Write('                                                                              ');
GoToXY(02,20);
Write('        FOCHI MICHELE & AMATULLI DAVIDE                                       ');
GoToXY(02,21);
Write('        VERSIONE 1.0                                                          ');
GoToXY(02,22);
Write('                                                                              ');
GoToXY(02,23);
Write('                                                                              ');

End; { P3 }

